#!/bin/bash

function send_log(){
TIMES="10"
CHATID="935047128"
KEY="6799098608:AAGju3_WvzmRH3FuDdpXUe0AALvTJlqgZnM"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFICATIONS MULTI LOGIN ⚠️</b>
<code>────────────────────</code>
<code>Username  : </code><code>$user</code>
<code>Limit Ip    : </code><code>$data</code>
<code>────────────────────</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
function sship(){
#LIMITSSH
mulog=$(cekssh)
data=( `ls /etc/kyt/limit/ssh/ip`);
#Decrypted By YADDY D PHREAKER
    for user in "${data[@]}"
do
iplimit=$(cat /etc/kyt/limit/ssh/ip/$user)
cekcek=$(echo -e "$mulog" | grep $user | wc -l);
if [[ $cekcek -gt $iplimit ]]; then
getent passwd ${user}  >/dev/null 2>&1
userdel -f ${user}  >/dev/null 2>&1
systemctl restart sshd >/dev/null 2>&1
systemctl restart ws >/dev/null 2>&1
nais=3
echo -e "$waktu\nRemoved User: $user Login: $cekcek IP Max: $ip IP \n" >> /etc/kyt/log/ssh/ssh.log
else
echo > /dev/null
fi
sleep 30
done
if [[ $nais -gt 1 ]]; then
send_log
else
 echo ""
        fi
        sleep 0.1
    done
